package com.example.lottary.ui.browse;

import android.Manifest;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Bundle;

import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.camera.core.CameraSelector;
import androidx.camera.core.ImageAnalysis;
import androidx.camera.core.ImageProxy;
import androidx.camera.view.CameraController;
import androidx.camera.view.LifecycleCameraController;
import androidx.camera.view.PreviewView;
import androidx.core.content.ContextCompat;

import com.example.lottary.R;
import com.google.android.material.button.MaterialButton;
import com.google.android.material.snackbar.Snackbar;
import com.google.mlkit.vision.barcode.BarcodeScanner;
import com.google.mlkit.vision.barcode.BarcodeScannerOptions;
import com.google.mlkit.vision.barcode.BarcodeScanning;
import com.google.mlkit.vision.barcode.common.Barcode;
import com.google.mlkit.vision.common.InputImage;

import java.util.concurrent.Executor;

/**
 * EventQrScannerActivity
 *
 * Opens camera, scans a QR code generated by QrScanActivity / QrCodeActivity.
 * The payload is a deep-link URL or bare event id. We parse it into an event id,
 * then launch EventDetailsActivity for that id.
 */
public class EventQrScannerActivity extends AppCompatActivity {

    private PreviewView preview;
    private LifecycleCameraController controller;
    private boolean handled = false; // one-shot guard

    private final ActivityResultLauncher<String> permLauncher =
            registerForActivityResult(
                    new ActivityResultContracts.RequestPermission(),
                    granted -> {
                        if (granted) {
                            startCamera();
                        } else {
                            Snackbar.make(
                                    findViewById(android.R.id.content),
                                    "Camera permission is required to scan QR codes.",
                                    Snackbar.LENGTH_LONG
                            ).show();
                        }
                    });

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_event_qr_scanner);

        preview = findViewById(R.id.preview);
        MaterialButton btnBack = findViewById(R.id.btn_back);

        btnBack.setOnClickListener(v -> finish());

        if (ContextCompat.checkSelfPermission(this, Manifest.permission.CAMERA)
                == PackageManager.PERMISSION_GRANTED) {
            startCamera();
        } else {
            permLauncher.launch(Manifest.permission.CAMERA);
        }
    }

    private void startCamera() {
        controller = new LifecycleCameraController(this);
        controller.setCameraSelector(
                new CameraSelector.Builder()
                        .requireLensFacing(CameraSelector.LENS_FACING_BACK)
                        .build()
        );
        controller.setImageAnalysisBackpressureStrategy(
                ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST
        );
        controller.setEnabledUseCases(CameraController.IMAGE_ANALYSIS);

        preview.setController(controller);
        controller.bindToLifecycle(this);

        BarcodeScannerOptions options = new BarcodeScannerOptions.Builder().build();
        BarcodeScanner scanner = BarcodeScanning.getClient(options);
        Executor mainExecutor = ContextCompat.getMainExecutor(this);

        controller.setImageAnalysisAnalyzer(mainExecutor, image -> analyze(scanner, image));
    }

    private void analyze(@NonNull BarcodeScanner scanner, @NonNull ImageProxy proxy) {
        if (handled) {
            proxy.close();
            return;
        }

        try {
            if (proxy.getImage() == null) {
                proxy.close();
                return;
            }
            InputImage img = InputImage.fromMediaImage(
                    proxy.getImage(),
                    proxy.getImageInfo().getRotationDegrees()
            );

            scanner.process(img)
                    .addOnSuccessListener(barcodes -> {
                        if (handled) return;
                        for (Barcode b : barcodes) {
                            String value = b.getRawValue();
                            String eventId = EventDetailsActivity.parseEventIdFromPayload(value);
                            if (eventId != null && !eventId.isEmpty()) {
                                handled = true;
                                Intent i = new Intent(this, EventDetailsActivity.class);
                                i.putExtra(EventDetailsActivity.EXTRA_EVENT_ID, eventId);
                                startActivity(i);
                                finish();
                                break;
                            }
                        }
                    })
                    .addOnCompleteListener(task -> proxy.close());
        } catch (Exception e) {
            proxy.close();
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (controller != null) {
            controller.clearImageAnalysisAnalyzer();
        }
    }
}



